/*
 * Copyright 2010-2021 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.idea.frontend.api.components;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TestMetadata;
import org.jetbrains.kotlin.test.TestRoot;
import org.junit.runner.RunWith;

/*
 * This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}.
 * DO NOT MODIFY MANUALLY.
 */
@SuppressWarnings("all")
@TestRoot("frontend-fir")
@TestDataPath("$CONTENT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
@TestMetadata("testData/components/expectedExpressionType")
public class ExpectedExpressionTypeTestGenerated extends AbstractExpectedExpressionTypeTest {
    private void runTest(String testDataFilePath) throws Exception {
        KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
    }

    @TestMetadata("functionExpressionBody.kt")
    public void testFunctionExpressionBody() throws Exception {
        runTest("testData/components/expectedExpressionType/functionExpressionBody.kt");
    }

    @TestMetadata("functionExpressionBodyQualified.kt")
    public void testFunctionExpressionBodyQualified() throws Exception {
        runTest("testData/components/expectedExpressionType/functionExpressionBodyQualified.kt");
    }

    @TestMetadata("functionExpressionBodyWithTypeFromRHS.kt")
    public void testFunctionExpressionBodyWithTypeFromRHS() throws Exception {
        runTest("testData/components/expectedExpressionType/functionExpressionBodyWithTypeFromRHS.kt");
    }

    @TestMetadata("functionExpressionBodyWithoutExplicitType.kt")
    public void testFunctionExpressionBodyWithoutExplicitType() throws Exception {
        runTest("testData/components/expectedExpressionType/functionExpressionBodyWithoutExplicitType.kt");
    }

    @TestMetadata("functionLambdaParam.kt")
    public void testFunctionLambdaParam() throws Exception {
        runTest("testData/components/expectedExpressionType/functionLambdaParam.kt");
    }

    @TestMetadata("functionNamedlParam.kt")
    public void testFunctionNamedlParam() throws Exception {
        runTest("testData/components/expectedExpressionType/functionNamedlParam.kt");
    }

    @TestMetadata("functionParamWithTypeParam.kt")
    public void testFunctionParamWithTypeParam() throws Exception {
        runTest("testData/components/expectedExpressionType/functionParamWithTypeParam.kt");
    }

    @TestMetadata("functionPositionalParam.kt")
    public void testFunctionPositionalParam() throws Exception {
        runTest("testData/components/expectedExpressionType/functionPositionalParam.kt");
    }

    @TestMetadata("functionPositionalParamQualified.kt")
    public void testFunctionPositionalParamQualified() throws Exception {
        runTest("testData/components/expectedExpressionType/functionPositionalParamQualified.kt");
    }

    @TestMetadata("ifCondition.kt")
    public void testIfCondition() throws Exception {
        runTest("testData/components/expectedExpressionType/ifCondition.kt");
    }

    @TestMetadata("ifConditionQualified.kt")
    public void testIfConditionQualified() throws Exception {
        runTest("testData/components/expectedExpressionType/ifConditionQualified.kt");
    }

    @TestMetadata("infixFunctionAsRegularCallParam.kt")
    public void testInfixFunctionAsRegularCallParam() throws Exception {
        runTest("testData/components/expectedExpressionType/infixFunctionAsRegularCallParam.kt");
    }

    @TestMetadata("infixFunctionParam.kt")
    public void testInfixFunctionParam() throws Exception {
        runTest("testData/components/expectedExpressionType/infixFunctionParam.kt");
    }

    @TestMetadata("infixFunctionParamQualified.kt")
    public void testInfixFunctionParamQualified() throws Exception {
        runTest("testData/components/expectedExpressionType/infixFunctionParamQualified.kt");
    }

    @TestMetadata("propertyDeclaration.kt")
    public void testPropertyDeclaration() throws Exception {
        runTest("testData/components/expectedExpressionType/propertyDeclaration.kt");
    }

    @TestMetadata("propertyDeclarationQualified.kt")
    public void testPropertyDeclarationQualified() throws Exception {
        runTest("testData/components/expectedExpressionType/propertyDeclarationQualified.kt");
    }

    @TestMetadata("propertyDeclarationWithTypeFromRHS.kt")
    public void testPropertyDeclarationWithTypeFromRHS() throws Exception {
        runTest("testData/components/expectedExpressionType/propertyDeclarationWithTypeFromRHS.kt");
    }

    @TestMetadata("propertyDeclarationWithoutExplicitType.kt")
    public void testPropertyDeclarationWithoutExplicitType() throws Exception {
        runTest("testData/components/expectedExpressionType/propertyDeclarationWithoutExplicitType.kt");
    }

    @TestMetadata("returnFromFunction.kt")
    public void testReturnFromFunction() throws Exception {
        runTest("testData/components/expectedExpressionType/returnFromFunction.kt");
    }

    @TestMetadata("returnFromFunctionQualifiedReceiver.kt")
    public void testReturnFromFunctionQualifiedReceiver() throws Exception {
        runTest("testData/components/expectedExpressionType/returnFromFunctionQualifiedReceiver.kt");
    }

    @TestMetadata("returnFromFunctionQualifiedSelector.kt")
    public void testReturnFromFunctionQualifiedSelector() throws Exception {
        runTest("testData/components/expectedExpressionType/returnFromFunctionQualifiedSelector.kt");
    }

    @TestMetadata("returnFromLambda.kt")
    public void testReturnFromLambda() throws Exception {
        runTest("testData/components/expectedExpressionType/returnFromLambda.kt");
    }

    @TestMetadata("variableAssignment.kt")
    public void testVariableAssignment() throws Exception {
        runTest("testData/components/expectedExpressionType/variableAssignment.kt");
    }

    @TestMetadata("variableAssignmentQualified.kt")
    public void testVariableAssignmentQualified() throws Exception {
        runTest("testData/components/expectedExpressionType/variableAssignmentQualified.kt");
    }

    @TestMetadata("whileCondition.kt")
    public void testWhileCondition() throws Exception {
        runTest("testData/components/expectedExpressionType/whileCondition.kt");
    }

    @TestMetadata("whileConditionQualified.kt")
    public void testWhileConditionQualified() throws Exception {
        runTest("testData/components/expectedExpressionType/whileConditionQualified.kt");
    }
}
